"""
Common resource for nerve centreline annotation terms.
"""

# convention: preferred name, preferred id, followed by any other ids and alternative names
nerve_terms = [
    ("vagus nerve", "UBERON:0001759", "ILX:0733375"),
    # flatmap points
    ("brain_44-1", ""),
    ("brain_12-1", ""),
    ("brain_34-1", ""),
    ("brain_33-1", ""),
    ("point_1", ""),
    ("ardell_4_branching_point", ""),
    ("ganglion_1-1", ""),
    ("bolser_X_1", ""),
    ("ardell_3_branching_point", ""),
    ("point_3", ""),
    ("label_1-1", ""),
    ("ganglion_2-1", ""),
    ("point_6", ""),
    ("point_7", ""),
    ("point_8", ""),
    ("point_9", ""),
    ("point_10", ""),
    ("label_4-1", ""),
    ("label_3-1", ""),
    ("label_2-1", ""),
    ("point_11", ""),
    ("point_13", ""),
    ("label_6-1", ""),
    ("label_5-1", ""),
    ("point_14", ""),
    ("cardio_4-1", ""),
    ("point_16", ""),
    ("point_18", ""),
    ("point_19", ""),
    ("point_20", ""),
    ("label_7-1", ""),
    ("label_8-1", ""),
    ("respiratory_11-1", ""),
    ("respiratory_5-1", ""),
    ("point_21", ""),
    ("label_10-1", ""),
    ("label_11-1", ""),
    ("label_12-1", ""),
    ("point_37", ""),
    ("bolser_X-5", ""),
    ("bolser_X-4", ""),
    ("external_laryngeal_n_branching_point", ""),
    ("plexus_2-1", ""),
    ("bolser_X-14", ""),
    ("label_15-1", ""),
    ("label_14-1", ""),
    ("bolser_X-15", ""),
    ("point_41", ""),
    ("point_22", ""),
    ("point_24", ""),
    ("point_25", ""),
    ("plexus_3-1", ""),
    ("point_26", ""),
    ("point_28", ""),
    ("label_9-1", ""),
    ("point_29", ""),
    ("label_15-1", ""),
    ("label_16-1", ""),
    ("label_17-1", ""),
    ("label_18-1", ""),
    ("label_19-1", ""),
    ("label_20-1", ""),
    ("label_21-1", ""),
    ("label_22-1", ""),
    ("label_13-1", ""),
    ("respiratory_8-1", ""),
    ("respiratory_11-1", ""),
    ("point_38", ""),
    ("bolser_X-2", ""),
    ("bolser_X-3", ""),
    ("point_30", ""),
    ("plexus_4-1", ""),
    ("point_31", ""),
    ("respiratory_17-1", ""),
    ("point_32", ""),
    ("point_33", ""),
    ("plexus_5-1", ""),
    ("digestive_12-1", ""),
    ("point_34", ""),
    ("brain_44-1", ""),
    ("digestive_9-1", ""),
    ("point_35", ""),
    ("plexus_6-1", ""),
    ("point_36", ""),
    ("urinary_13-1", ""),
    ("brain_D_1", ""),
    # flatmap segments
    ("ardell_3", ""),
    ("ardell_4", ""),
    ("bolser_1", ""),
    ("bolser_2", ""),
    ("bolser_3", ""),
    ("bolser_4", ""),
    ("bolser_5", ""),
    ("bolser_14", ""),
    ("bolser_15", ""),
    ("n_1", ""),
    ("n_2", ""),
    ("n_3", ""),
    ("n_4", ""),
    ("n_5", ""),
    ("n_6", ""),
    ("n_68", ""),
    ("n_7", ""),
    ("n_8", ""),
    ("n_9", ""),
    ("n_10", ""),
    ("n_11", ""),
    ("n_12", ""),
    ("n_13", ""),
    ("n_14", ""),
    ("n_15", ""),
    ("n_16", ""),
    ("n_17", ""),
    ("n_18", ""),
    ("n_19", ""),
    ("n_20", ""),
    ("n_21", ""),
    ("n_22", ""),
    ("n_23", ""),
    ("n_24", ""),
    ("n_25", ""),
    ("n_26", ""),
    ("n_27", ""),
    ("n_28", ""),
    ("n_29", ""),
    ("n_30", ""),
    ("n_31", ""),
    ("n_32", ""),
    ("n_33", ""),
    ("n_34", ""),
    ("n_35", ""),
    ("n_36", ""),
    ("n_37", ""),
    ("n_38", ""),
    ("n_39", ""),
    ("n_40", ""),
    ("n_41", ""),
    ("n_42", ""),
    ("n_43", ""),
    ("n_44", ""),
    ("n_45", ""),
    ("n_46", ""),
    ("n_47", ""),
    ("n_48", ""),
    ("n_49", ""),
    ("n_50", ""),
    ("n_51", ""),
    ("n_52", ""),
    ("n_53", ""),
    ("n_54", ""),
    ("n_55", ""),
    ("n_56", ""),
    ("n_57", ""),
    ("n_58", ""),
    ("n_59", ""),
    ("n_60", ""),
    ("n_61", ""),
    ("n_62", ""),
    ("n_63", ""),
    ("n_64", ""),
    ("n_65", ""),
    ("n_66", ""),
    ("n_67", ""),
    ]

def get_nerve_term(name : str):
    """
    Find term by matching name to any identifier held for a term.
    Raise exception if name not found.
    :return ( preferred name, preferred id )
    """
    for term in nerve_terms:
        if name in term:
            return ( term[0], term[1] )
    raise NameError("Nerve annotation term '" + name + "' not found.")
