name: Deploy library

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release-package:
    if: github.repository == 'ABI-Software/scaffoldmaker'
    runs-on: ubuntu-24.04
    name: Release package
    permissions:
      contents: write
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Release Python package
        uses: hsorby/release-python-package-action@v2
        with:
          pypi-package-name: scaffoldmaker
